/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface RouterFactoryInterface extends Interface {
    getFunction(nameOrSignature: "deployRouter" | "getUserRouters" | "getVault" | "owner" | "routerImplementation" | "tokenToVault" | "userRouters" | "whitelistVault"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RouterDeployed" | "VaultWhitelisted"): EventFragment;

    encodeFunctionData(functionFragment: 'deployRouter', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserRouters', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'routerImplementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenToVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userRouters', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'whitelistVault', values: [AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'deployRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserRouters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'routerImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenToVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userRouters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'whitelistVault', data: BytesLike): Result;
  }

  
    export namespace RouterDeployedEvent {
      export type InputTuple = [owner: AddressLike, router: AddressLike];
      export type OutputTuple = [owner: string, router: string];
      export interface OutputObject {owner: string, router: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultWhitelistedEvent {
      export type InputTuple = [token: AddressLike, vault: AddressLike];
      export type OutputTuple = [token: string, vault: string];
      export interface OutputObject {token: string, vault: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RouterFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): RouterFactory;
    waitForDeployment(): Promise<this>;

    interface: RouterFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    deployRouter: TypedContractMethod<
      [operatingPct: BigNumberish, treasuryPct: BigNumberish, lockedPct: BigNumberish, allowanceAmount: BigNumberish, allowancePeriod: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    getUserRouters: TypedContractMethod<
      [user: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getVault: TypedContractMethod<
      [token: AddressLike, ],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    routerImplementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenToVault: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    userRouters: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    whitelistVault: TypedContractMethod<
      [token: AddressLike, vault: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'deployRouter'): TypedContractMethod<
      [operatingPct: BigNumberish, treasuryPct: BigNumberish, lockedPct: BigNumberish, allowanceAmount: BigNumberish, allowancePeriod: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getUserRouters'): TypedContractMethod<
      [user: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getVault'): TypedContractMethod<
      [token: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'routerImplementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenToVault'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'userRouters'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'whitelistVault'): TypedContractMethod<
      [token: AddressLike, vault: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'RouterDeployed'): TypedContractEvent<RouterDeployedEvent.InputTuple, RouterDeployedEvent.OutputTuple, RouterDeployedEvent.OutputObject>;
getEvent(key: 'VaultWhitelisted'): TypedContractEvent<VaultWhitelistedEvent.InputTuple, VaultWhitelistedEvent.OutputTuple, VaultWhitelistedEvent.OutputObject>;

    filters: {
      
      'RouterDeployed(address,address)': TypedContractEvent<RouterDeployedEvent.InputTuple, RouterDeployedEvent.OutputTuple, RouterDeployedEvent.OutputObject>;
      RouterDeployed: TypedContractEvent<RouterDeployedEvent.InputTuple, RouterDeployedEvent.OutputTuple, RouterDeployedEvent.OutputObject>;
    

      'VaultWhitelisted(address,address)': TypedContractEvent<VaultWhitelistedEvent.InputTuple, VaultWhitelistedEvent.OutputTuple, VaultWhitelistedEvent.OutputObject>;
      VaultWhitelisted: TypedContractEvent<VaultWhitelistedEvent.InputTuple, VaultWhitelistedEvent.OutputTuple, VaultWhitelistedEvent.OutputObject>;
    
    };
  }