/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'ISmartRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISmartRouter__factory>
getContractFactory(name: 'RouterFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RouterFactory__factory>
getContractFactory(name: 'IRouterFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRouterFactory__factory>
getContractFactory(name: 'SmartRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SmartRouter__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'MockERC4626Vault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC4626Vault__factory>

  getContractAt(name: 'ISmartRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISmartRouter>
getContractAt(name: 'RouterFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RouterFactory>
getContractAt(name: 'IRouterFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRouterFactory>
getContractAt(name: 'SmartRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SmartRouter>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'MockERC4626Vault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC4626Vault>

  deployContract(name: 'ISmartRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISmartRouter>
deployContract(name: 'RouterFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RouterFactory>
deployContract(name: 'IRouterFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRouterFactory>
deployContract(name: 'SmartRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SmartRouter>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockERC4626Vault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC4626Vault>

  deployContract(name: 'ISmartRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISmartRouter>
deployContract(name: 'RouterFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RouterFactory>
deployContract(name: 'IRouterFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRouterFactory>
deployContract(name: 'SmartRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SmartRouter>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockERC4626Vault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC4626Vault>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  