/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockCToken } from './MockCToken.js';
export type { MockERC20 } from './MockERC20.js';
export type { MockERC4626Vault } from './MockERC4626Vault.js';